### ISSUE TITLE
PhoneNo Validator

### ISSUE THREAD

**Issue by Bistika** [iteahome/team-project-online-shop#19]
Create a validator to check for Romanian phone numbers format.

**Comment by szocsmihai** [comment]
Keep in mind that a phone number for Romania can be written many different ways (as in different people write it different ways, but phones accept all of the following):

- No country prefix:
0753783133
0753 783 133
0753 78 31 33
etc.

- +40 (Romania) prefix:
+40753783133
+40 753 783 133 (this is how I write numbers, FYI)
etc.

- 0040 (Romania) prefix:
0040753783133
0040 753 783 133
etc.

**The common logic is**:
- **optional** "**+40**" or "**0040**" at the very start followed by **9 numeric digits**
or:
- if **no country code**: **10 numeric digits**, always starting with "**0**"
+ beware: "**whitespace**" character, "**.**" (dot) and "**-**" (dash) can all appear anywhere in the number.

Remeber!
- "+40" and "0040" mean Romania. After that, there are many, many options, depending on the phone service provider, the County (in the case of landlines). Regardless of the situation (mobile or landline), the rest of the phone number will always be 9 numeric digits, with or without the mentioned separators.

**Comment by Bistika** [comment]
There is a formatter which should turn the number always to this format 0040000000000.
the validators should only check if the output of the formatter matches this.
