### ISSUE TITLE
Create UserAccountUI

### ISSUE THREAD

**Issue by szocsmihai** [iteahome/team-project-online-shop#53]
We need a UI for the users to manage their account.

**Comment by szocsmihai** [comment]
I think I might have missed a step. The UI should go through a UserService to use DAO features.
**@Bistika**: Should we add update and delete methods to UserService?

**Comment by Bistika** [comment]
@szocsmihai  Yeap, it could not be added so far because we were missing the DAO part. Lets see that the DAO part is working just right for User and Product, and then proceed to add the missing methods on Service, and further develop UI.
