### ISSUE TITLE
Forgive Misu :))

### ISSUE THREAD

**Issue by szocsmihai** [iteahome/team-project-online-shop#9]
I made some modifications to the code you posted, but forgot to branch out so that I could create a pull request, so I worked directly in develop. Oops, sorry. 
P.S.: is there a way to communicate on GitHub directly to another user? Creating an issue to convey a message is obviously over the top. Thanks.

**Comment by Bistika** [comment]
Tested the new push in develop and it works ok. We can let it as it. 
I do not think there is a github messaging platform :)
